In [507]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_validate, KFold, TimeSeriesSplit
from sklearn.linear_model import RANSACRegressor
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [508]:
targets = pd.read_excel('dataset/target.xlsx',  index_col=0)
features = pd.read_excel('dataset/features.xlsx', index_col=0)
cr = pd.read_excel("dataset/CREDIT_RATINGS.xlsx", index_col=0)

In [509]:
ft = ['OPER_MARGIN',
 'TOT_DEBT_TO_TOT_EQY',
 'TOT_DEBT_TO_EBITDA',
 'EBITDA_TO_TOT_INT_EXP',
 'RETURN_ON_ASSET',
 'ASSET_TURNOVER']

In [173]:
uv1 = cr[["Moody's Long Term Rating"]].dropna().index.to_list()
uv2 =cr['S&P LT Local Currency Issuer Credit Rating'].dropna().index.to_list()

In [174]:
universe = list(np.unique(uv1 + uv2))

In [510]:
X = features.copy().dropna()[ft]
y = targets[['numeric_rating']].loc[X.index]


In [229]:
universe = [u for u in universe if u in X.index.to_list()]

In [457]:
n = 2
cv = cross_validate(model, X, y, cv=KFold(n, shuffle=True), return_estimator=True)
ft = np.mean([cv['estimator'][x].feature_importances_ for x in range(n)], axis=0)

In [458]:
ft

array([0.36715843, 0.04890454, 0.29630885, 0.15889085, 0.12873734,
       0.        ])

In [517]:
model.

DecisionTreeRegressor()

In [462]:
fft = []
for n in range(2, 10):
    for _ in range(10):
        cv = cross_validate(model, X, y, cv=KFold(n, shuffle=True), return_estimator=True)
        ft = np.mean([cv['estimator'][x].feature_importances_ for x in range(n)], axis=0)

        fft.append(ft)

In [496]:
a = np.mean(fft, axis=0).round(2)

In [497]:
a

array([0.05, 0.14, 0.23, 0.34, 0.15, 0.1 ])

In [500]:
l = a[4:]

In [502]:
l.sum()

0.25

In [503]:
l /= l.sum()

In [504]:
l = l.round(2)

In [505]:
l

array([0.6, 0.4])

In [467]:
X.columns

Index(['OPER_MARGIN', 'TOT_DEBT_TO_TOT_EQY', 'TOT_DEBT_TO_EBITDA',
       'EBITDA_TO_TOT_INT_EXP', 'RETURN_ON_ASSET', 'ASSET_TURNOVER'],
      dtype='object')

In [524]:
y.to_excel("t.xlsx")

In [33]:
def _determine_credit_rating(weighted_score):
    credit_ratings = {
        2.5: "Aaa",
        3.5: "Aa",
        4.5: "A",
        5.5: "Baa",
        6.5: "Ba",
        7.5: "B",
        8.5: "Caa",
        9.5: "Ca",
        10: "C",
    }
    return credit_ratings.get(max(filter(lambda x: x <= weighted_score, credit_ratings.keys()), default=2.5), "Aaa")

In [36]:
_determine_credit_rating()

'Aaa'

In [32]:
_determine_credit_rating(2.4)

'Aaa'

In [37]:
def _determine_credit_rating(weighted_score):
    credit_ratings = {
        "Aaa": 2.5,
        "Aa": 3.5,
        "A": 4.5,
        "Baa": 5.5,
        "Ba": 6.5,
        "B": 7.5,
        "Caa": 8.5,
        "Ca": 9.5,
        "C": float("inf")
    }
    return next(rating for rating, threshold in credit_ratings.items() if weighted_score <= threshold)

In [41]:
_determine_credit_rating(3.5)

'Aa'